export type StatusTone = "neutral" | "info" | "success" | "warning" | "danger";

const TONE_BY_STATUS: Record<string, StatusTone> = {
  submitted: "info",
  under_review: "info",
  needs_information: "warning",
  qualified: "info",
  declined: "danger",
  converted: "success",
  draft: "neutral",
  sent: "info",
  accepted: "success",
  rejected: "danger",
  expired: "warning",
  superseded: "neutral",
  planned: "info",
  active: "success",
  on_hold: "warning",
  completed: "success",
  cancelled: "danger",
  issued: "info",
  partially_paid: "warning",
  paid: "success",
  void: "danger",
  overdue: "danger",
  succeeded: "success",
  failed: "danger",
  refunded: "warning",
  partially_refunded: "warning",
  review_required: "warning",
  pending_payment: "warning",
  processing: "info",
  recorded: "success",
  unread: "info",
  read: "neutral",
  available: "success",
  limited: "warning",
  unavailable: "neutral",
  owner: "info",
  member: "neutral",
  submitted_deliverable: "info",
  todo: "neutral",
  in_progress: "info",
  blocked: "warning",
  changes_requested: "warning",
  customer: "info",
  project_team: "neutral",
  internal: "neutral",
  pending: "warning",
  enabled: "success",
  disabled: "neutral",
  accepted_invitation: "success",
  revoked: "danger",
};

export function statusTone(status: string): StatusTone {
  return TONE_BY_STATUS[status] ?? "neutral";
}
